### ISSUE TITLE
[Debug Watch] Hot reload on debug, python autocompletion based on container runtime

### ISSUE THREAD

**Issue by mr-bjerre** [GoogleCloudPlatform/cloud-code-vscode#356] opened 2020-12-17 21:26 UTC
**Use case**

I'm trying to set up a great development workspace in VSCode. 

I was inspired by the sample app from Cloud Code flask guestbook app. I downloaded the sample, went to debug tab and started everything in minikube. Everything spins up just fine and when I was prompted for the front- and backend folders for debugging I put in `/app` so my `launch.json` now looks like this

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run on Kubernetes",
      "type": "cloudcode.kubernetes",
      "request": "launch",
      "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
      "watch": true,
      "cleanUp": true,
      "portForward": true,
      "debug": [
        {
          "image": "python-guestbook-frontend",
          "sourceFileMap": {
            "${workspaceFolder}/src/frontend": "/app"
          }
        },
        {
          "image": "python-guestbook-backend",
          "sourceFileMap": {
            "${workspaceFolder}/src/backend": "/app"
          }
        }
      ]
    }
  ]
}
```

**Feature**

I would like the following features to be in place:
1.Be able to set breakpoints in VSCode for my services, whether its a React app or a flask backend.
2. Autocompletion (e.g. using python and pylance extension for python containers) based on the containers runtime instead of using my local/host python runtime.
3. Hot reload on changes

I'm not sure if this is already possible and its just a matter of configuration that I'm not able to get exactly right?

**Comment by mr-bjerre** [comment] 2020-12-17 21:55
Wait actually point 1 works - the breakpoints but 2 and 3 doesn't

**Comment by redborian** [comment] 2020-12-22 19:20
Thanks for trying out our extension, @mr-bjerre. We are glad that (1) works for you. (2) is something that is outside of our control as it is a different extension. Hot reloading is not possible when you "Start Debugging". However, if you choose "Run without debugging" option, hot reloading will be supported. We will be glad to clarify if you face any other issues.

**Comment by sivakku** [comment] 2021-03-29 22:53
Thanks, as mentioned above auto completion is outside our extension, Hot reloading on run option is supported and we are looking in the roadmap for hot reload on debug(dupe of #400)

**Closed by sivakku** 2021-03-29 22:53 UTC
Labels: Reassess in the future, area/debugging, kind/enhancement
