### ISSUE TITLE
VSCode extension hangs on "Generating Suggestion"

### ISSUE THREAD

**Issue by nonki72** [GoogleCloudPlatform/cloud-code-vscode#918] opened 2024-07-04 22:59 UTC
**Environment**:

python --version
Python 3.10.14

conda --version
conda 23.9.0

pip --version
pip 24.0 from /home/jordan/.conda/envs/logoscpu/lib/python3.10/site-packages/pip (python 3.10)

**Version information**

Cloud Code Extension version:

Name: Gemini Code Assist + Google Cloud Code
Id: googlecloudtools.cloudcode
Description: Gemini Code Assist + Tools for Google Cloud
Version: 2.13.0
Publisher: Google Cloud
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode

VSCode version:

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:43:07.605Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.11-200.fc39.x86_64

Python Extension:

Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2024.8.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

Pylance Extension:

Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2024.6.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

All extensions:
[
	{
		"identifier": {
			"id": "vscode.bat"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.builtin-notebook-renderers"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.clojure"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.coffeescript"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.configuration-editing"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.cpp"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.csharp"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.css"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.css-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.dart"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.debug-auto-launch"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.debug-server-ready"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.diff"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.docker"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.emmet"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.extension-editing"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.fsharp"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.git"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.git-base"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.github"
		},
		"preRelease": false,
		"version": "0.0.1",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.github-authentication"
		},
		"preRelease": false,
		"version": "0.0.2",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.go"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.groovy"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.grunt"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.gulp"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.handlebars"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.hlsl"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.html"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.html-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.ini"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.ipynb"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.jake"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.java"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.javascript"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.json"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.json-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.julia"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.latex"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.less"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.log"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.lua"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.make"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.markdown"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.markdown-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.markdown-math"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.media-preview"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.merge-conflict"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.microsoft-authentication"
		},
		"preRelease": false,
		"version": "0.0.1",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.npm"
		},
		"preRelease": false,
		"version": "1.0.1",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.objective-c"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.perl"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.php"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.php-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.powershell"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.pug"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.python"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.r"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.razor"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.references-view"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.restructuredtext"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.ruby"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.rust"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.scss"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.search-result"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.shaderlab"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.shellscript"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.simple-browser"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.sql"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.swift"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-abyss"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-defaults"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-kimbie-dark"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-monokai"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-monokai-dimmed"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-quietlight"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-red"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-solarized-dark"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-solarized-light"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.theme-tomorrow-night-blue"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.tunnel-forwarding"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.typescript"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.typescript-language-features"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.vb"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.vscode-theme-seti"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.xml"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "vscode.yaml"
		},
		"preRelease": false,
		"version": "1.0.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "dbaeumer.vscode-eslint",
			"uuid": "583b2b34-2c1e-4634-8c0b-0b82e283ea3a"
		},
		"preRelease": false,
		"version": "2.4.2",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "firefox-devtools.vscode-firefox-debug",
			"uuid": "c5f4d87f-a524-462c-ac01-923eb19cf3e9"
		},
		"preRelease": false,
		"version": "2.9.10",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "github.vscode-github-actions",
			"uuid": "04f49bfc-8330-4eee-8237-ea938fb755ef"
		},
		"preRelease": false,
		"version": "0.26.2",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "googlecloudtools.cloudcode",
			"uuid": "5e8803a2-3dc8-42b3-9c5f-ea9d37828c03"
		},
		"preRelease": false,
		"version": "2.1.1",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "ms-python.debugpy",
			"uuid": "4bd5d2c9-9d65-401a-b0b2-7498d9f17615"
		},
		"preRelease": false,
		"version": "2024.2.0",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "ms-python.python",
			"uuid": "f1f59ae4-9318-4f3c-a9b5-81b2eaa5f8a5"
		},
		"preRelease": false,
		"version": "2024.2.1",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "ms-python.vscode-pylance",
			"uuid": "364d2426-116a-433a-a5d8-a5098dc3afbd"
		},
		"preRelease": false,
		"version": "2024.3.2",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "ms-vscode.js-debug",
			"uuid": "25629058-ddac-4e17-abba-74678e126c5d"
		},
		"preRelease": false,
		"version": "1.82.0",
		"pinned": false
	},
	{
		"identifier": {
			"id": "ms-vscode.js-debug-companion",
			"uuid": "99cb0b7f-7354-4278-b8da-6cc79972169d"
		},
		"preRelease": false,
		"version": "1.1.2",
		"pinned": false
	},
	{
		"identifier": {
			"id": "ms-vscode.vscode-js-profile-table",
			"uuid": "7e52b41b-71ad-457b-ab7e-0620f1fc4feb"
		},
		"preRelease": false,
		"version": "1.0.3",
		"pinned": false
	},
	{
		"identifier": {
			"id": "mtxr.sqltools",
			"uuid": "6a2bbab0-d8f0-43fa-9b26-e6a3b7892a0b"
		},
		"preRelease": false,
		"version": "0.28.1",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "reditorsupport.r",
			"uuid": "4dfff9f4-ff9b-47bb-b0d1-c54e18d8febb"
		},
		"preRelease": false,
		"version": "2.8.4",
		"pinned": false,
		"installed": true
	},
	{
		"identifier": {
			"id": "tabnine.tabnine-vscode",
			"uuid": "75da638c-c45a-44ea-aa3b-8570a3559810"
		},
		"preRelease": false,
		"version": "3.35.0",
		"pinned": false,
		"installed": true
	}
]

OS: 

uname -a
Linux fedora 6.8.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024 x86_64 GNU/Linux

Conda environment:

conda list
# packages in environment at /home/jordan/.conda/envs/logoscpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
accelerate                0.31.0                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
benepar                   0.2.0                    pypi_0    pypi
blas                      1.0                         mkl  
brotli-python             1.0.9           py310h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2023.08.22           h06a4308_0    anaconda
catalogue                 2.0.10          py310hff52083_0    conda-forge
category-encoders         2.6.3                    pypi_0    pypi
certifi                   2023.11.17      py310h06a4308_0    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpathlib              0.13.0          py310hff52083_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
confection                0.1.4           py310h17c5347_0    conda-forge
cpuonly                   2.0                           0    pytorch
cymem                     2.0.6           py310h295c915_0  
cython-blis               0.7.10          py310h1f7b6fc_2    conda-forge
dnspython                 2.6.1                    pypi_0    pypi
emoji                     2.12.1                   pypi_0    pypi
en-core-web-lg            3.7.1                    pypi_0    pypi
en-core-web-md            3.7.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py310h06a4308_0  
flatbuffers               24.3.25                  pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
gensim                    4.3.2                    pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py310heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.64.1                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
huggingface-hub           0.23.4                   pypi_0    pypi
idna                      3.7             py310h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4           py310h06a4308_0  
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
keras                     3.4.1                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
langcodes                 3.3.0              pyhd3eb1b0_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libclang                  18.1.1                   pypi_0    pypi
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp-base              1.3.2                h5eee18b_0  
llvm-openmp               14.0.6               h9e868ea_0  
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py310h5eee18b_0  
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.8           py310h5eee18b_0  
mkl_random                1.2.4           py310hdb19cb5_0  
ml-dtypes                 0.3.2                    pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0           py310h06a4308_0  
multidict                 6.0.5                    pypi_0    pypi
murmurhash                1.0.7           py310h295c915_0  
namex                     0.0.8                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1           py310h06a4308_0  
nltk                      3.8.1                    pypi_0    pypi
nn                        0.1.1                    pypi_0    pypi
numpy                     1.26.4          py310h5f9d8c6_0  
numpy-base                1.26.4          py310hb5e798b_0  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.3.1                h4ab18f5_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
optree                    0.11.0                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
path                      16.14.0                  pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    10.3.0          py310h5eee18b_0  
pip                       24.0            py310h06a4308_0  
preshed                   3.0.6           py310h295c915_0  
protobuf                  4.25.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pyarrow                   16.0.0                   pypi_0    pypi
pydantic                  2.0.3           py310h2372a71_0    conda-forge
pydantic-core             2.3.0           py310hcb5633a_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pymongo                   4.8.0                    pypi_0    pypi
pymongoarrow              1.4.0                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.14              h955ad1f_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytorch                   2.3.1              py3.10_cpu_0    pytorch
pytorch-metric-learning   2.5.0                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1           py310h5eee18b_0  
readline                  8.2                  h5eee18b_0  
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.2          py310h06a4308_0  
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.5.0                    pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                69.5.1          py310h06a4308_0  
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
spacy                     3.7.2           py310h3c18c91_0  
spacy-legacy              3.0.12             pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.5              pyhd8ed1ab_0    conda-forge
spacy-stanza              1.0.4                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
srsly                     2.4.8           py310h6a678d5_1  
stanza                    1.6.1                    pypi_0    pypi
statsmodels               0.14.2                   pypi_0    pypi
sympy                     1.12            py310h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.16.2                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
thinc                     8.2.2           py310h3c18c91_0  
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.19.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torch-struct              0.5                      pypi_0    pypi
torchaudio                2.3.1                 py310_cpu    pytorch
torchvision               0.18.1                py310_cpu    pytorch
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
transformers              4.42.3                   pypi_0    pypi
typer                     0.9.4              pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0          py310h06a4308_0  
typing_extensions         4.11.0          py310h06a4308_0  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2           py310h06a4308_0  
wasabi                    1.1.2           py310hff52083_1    conda-forge
weasel                    0.3.4           py310h06a4308_0  
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0          py310h06a4308_0  
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.9.4                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2  

Cloud SDK:

gcloud version
Google Cloud SDK 479.0.0
alpha 2024.05.31
beta 2024.05.31
bq 2.1.5
bundled-python3-unix 3.11.8
cloud-datastore-emulator 2.3.1
cloud-run-proxy 0.5.0
core 2024.05.31
gcloud-crc32c 1.0.0
gsutil 5.29

gcloud info
Google Cloud SDK [479.0.0]

Platform: [Linux, x86_64] uname_result(system='Linux', node='fedora', release='6.8.11-200.fc39.x86_64', version='#1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024', machine='x86_64')
Locale: ('en_US', 'UTF-8')
Python Version: [3.11.8 (main, Mar  6 2024, 21:56:16) [Clang 17.0.6 ]]
Python Location: [/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/bin/python3]
OpenSSL: [OpenSSL 3.0.13 30 Jan 2024]
Requests Version: [2.25.1]
urllib3 Version: [1.26.9]
Default CA certs file: [/usr/lib64/google-cloud-sdk/lib/third_party/certifi/cacert.pem]
Site Packages: [Enabled]

Installation Root: [/usr/lib64/google-cloud-sdk]
Installed Components:
  bundled-python3-unix: [3.11.8]
  alpha: [2024.05.31]
  gsutil: [5.29]
  core: [2024.05.31]
  cloud-datastore-emulator: [2.3.1]
  beta: [2024.05.31]
  bq: [2.1.5]
  gcloud-crc32c: [1.0.0]
  cloud-run-proxy: [0.5.0]
System PATH: [/home/jordan/.conda/envs/logoscpu/bin:/usr/condabin:/usr/local/cuda-12.1/bin:/home/jordan/.pyenv/shims:/home/jordan/.pyenv/bin:/home/jordan/.nvm/versions/node/v20.11.0/bin:/home/jordan/.local/bin:/home/jordan/bin:/usr/local/cuda-12.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin]
Python PATH: [/usr/lib64/google-cloud-sdk/lib/third_party:/usr/lib64/google-cloud-sdk/lib:/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/lib/python311.zip:/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/lib/python3.11:/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/lib/python3.11/lib-dynload:/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/lib/python3.11/site-packages:/home/jordan/.local/lib/python3.11/site-packages]
Cloud SDK on PATH: [False]
Kubectl on PATH: [False]

Installation Properties: [/usr/lib64/google-cloud-sdk/properties]
User Config Directory: [/home/jordan/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/home/jordan/.config/gcloud/configurations/config_default]

Account: [None]
Project: [None]
Universe Domain: [googleapis.com]

Current Properties:
  [core]
    disable_usage_reporting: [True] (property file)

Logs Directory: [/home/jordan/.config/gcloud/logs]
Last Log File: [/home/jordan/.config/gcloud/logs/2024.07.04/18.45.02.738517.log]

git: [git version 2.45.1]
ssh: [OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023]

Skaffold: 

Kubectl:

**Description**:

When coding in python with Visual Studio Code, pressing CTRL-ENTER displays the text: "Generating Suggestion..." and doesn't return a suggestion. 

**Repro step**:
Open VSCode
Install Gemini extension
Install other extensions
Create a *.py file
Enter the following code comment(example):
- # solve fizz-buzz problem
press the generate command keybinding: {CTRL-ENTER}
Wait for suggestion
if successful, keep coding and asking for suggestions
if working as expected, run some resource consuming applications in the background, such as an LLM model or web browser with many tabs
eventually it will stall waiting for a response
if it doesn't stall, then try using my specific hardware:
https://www.amazon.com/gp/product/B0CD2FX59R/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
ASUS ROG Strix G15 Gaming Laptop | 15.6" WQHD 165Hz 100% DCI-P3 | AMD 8-Core Ryzen 7 6800H (>i7-11370H) | 16GB DDR5 1TB SSD | GeForce RTX 3060 6GB Graphics | USB-C Backlit Win11Pro + HDMI Cable

**Comment by nonki72** [comment] 2024-07-04 23:10
If I disable the extension and restart and enable it again, the issue seems to be resolved. However, after a few minutes or hours of coding, it will happen again. To have to keep restarting the extension, it is a bit of a hassle. I am not using application default credentials at the moment. I'm using my Google Cloud platform account with the web based (Oauth-like) login.

**Comment by nonki72** [comment] 2024-07-04 23:14
One avenue to pursue while debugging this problem is to see if another recommendation engine is interfering with Gemini. I am using Tabnine Advanced, Hybrid model mode (Engine Version: 4.176.0-60). Both Tabnine and Gemini are activated.

Extension details:
Name: Tabnine: AI Autocomplete & Chat for Javascript, Python, Typescript, PHP, Go, Java & more
Id: TabNine.tabnine-vscode
Description: AI coding assistant with AI code completions and AI code chat right in the IDE, helping developers by generating code, writing unit tests and documentation, explaining legacy code, and much more. Tabnine supports all major languages including JavaScript, Python, Java, Typescript c/c++ and more.
Version: 3.121.0
Publisher: TabNine
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode

**Comment by davidponder** [comment] 2024-07-09 20:09
Hello!

Unfortunately due to VS Code limitations, VS Code will wait for all providers to return results (including Gemini and Tabnine) before resolving. As such, this is a known limitation within the IDE, and not specific to Gemini.

However, if you are able to reproduce this issue, using "Send Feedback" from within the extension will capture the logs and allow us to confirm this is the source of the problem. Those logs would be a tremendous help.

Since submitting feedback in that fashion will create a tracking bug on our end, I will close this for now and link to the internal item that feedback report will open. Thanks!

**Closed as completed by davidponder** 2024-07-09 20:09 UTC
