### ISSUE TITLE
Creating an issue from VS Code on OSX give the following starter text

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/cloud-code-vscode#123] opened 2019-07-11 16:05 UTC
**Environment**%3A%0AExtension%20version%3A%200.0.9%0AVSCode%20version%3A%201.36.1%0AOS%3A%20darwin%0A%0A**Description**%3A%0A%0A**Repro%20step**%3A

**Comment by redborian** [comment] 2019-07-12 15:43
Thanks @iantalarico for reporting this issue. This was caused by escaping the string twice. This has been fixed in our upcoming release.

**Comment by redborian** [comment] 2019-07-12 17:59
This has been fixed in the latest release.

**Closed by redborian** 2019-07-12 17:59 UTC
Labels: bug, in-next-release, p1
