### ISSUE TITLE
ability to pass environment variables to the skaffold.yaml

### ISSUE THREAD

**Issue by dsaydon90** [GoogleCloudPlatform/cloud-code-vscode#378] opened 2021-02-03 15:33 UTC
**Use case**

I'm working with `buildArgs` in my `skaffold.yaml` in order to pass argument to my `docker build`. The thing is that I'm using the `skaffold` syntax to add values from environment variables: `{{.ENV}}`

my `skaffold.yaml`

```
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
  - image: project
    context: "../Application"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        FOO: "{{.BAR}}"
    sync:
      infer:
      - '**/*'
...
```
**Feature**
add the ability to create env vars so the `skaffold` will be able to use them while the evaluation

**Comment by j-windsor** [comment] 2021-02-04 00:57
Thanks for the suggestion! We will put this on the backlog an

**Comment by j-windsor** [comment] 2021-02-04 01:06
Thanks for your suggestion! We can take a look at this, but we do support scenarios such as this using Skaffold profiles. You can use multiple [skaffold profiles](https://skaffold.dev/docs/environment/profiles/) to adjust your Skaffold build for certain contexts. You can specify the profile you would like to use in the VS Code launch config. _This is the preferred way to handle your situation._

If that does not work for your scenario for some reason, you can always open VS Code with any environment variables you want. These environment variables will get passed on to the Skaffold process that Cloud Code spawns.

Do either of these work for you?

**Comment by dsaydon90** [comment] 2021-02-04 09:34
Thank you for your suggestions

1. I can't use profiles because the argument that I'm trying to pass to the docker is a `token` so I can't to put an hard coded `token` in my `skaffold.yaml` due to security reasons, but I can put it in the `launch.json` because it's git ignored
2. it might be a challenge to pass environment variable to the vs code on Windows
3. It will be awesome to have support of env vars in the `launch.json` like they have it here
https://stackoverflow.com/a/48609350/4875299

**Comment by j-windsor** [comment] 2021-02-04 17:35
Ahh ok I understand. I'll put this on our internal backlog. Thanks!

**Comment by kschaab** [comment] 2021-02-04 18:38
For a work around you can spawn code with the environment variables you want, we send all the environment variables when we fork skaffold.

**Comment by aliusmiles** [comment] 2021-02-08 13:03
Another usecase for env vars: setting AWS_PROFILE so skaffold can push to ECR with correct credentials if local setup has multiple aws profiles.

Also it could be used to set KUBECONFIG as well (we have kubeconfig file per cluster). Because I haven't found yet how to set different kubectl contexts per repo/launch.json. I guess recommended workflow is multiple clusters per kubeconfig file, kubeconfig file path set in extension settings and then use skaffold's profiles to set context?

**Comment by sivakku** [comment] 2021-03-08 23:45
We are working on this one for our next release.

**Comment by sivakku** [comment] 2021-03-24 21:03
Remaining work is a dupe of [skaffold#4295](https://github.com/GoogleContainerTools/skaffold/issues/4295). Closing this work item.

**Closed by sivakku** 2021-03-24 21:03 UTC
Labels: area/debugging, area/skaffold, in-next-release, kind/enhancement

**Comment by pfinnerty** [comment] 2022-03-21 19:39
@sivakku I am running into this same error now too - but I was able to debug with the environment variables previously. Did something change in the most recent release?

**Comment by Ragurj1994** [comment] 2022-04-16 17:20
@sivakku Hi, I am running into the same issue as well. I need to pass in certain environment variables to be used by Helm. The environment variables are passed as helm values in the skaffold.yaml file. I am unable to find a way to pass environment variables to the Skaffold process while triggering the cloud code extension from VSCode. Any advice?

**Comment by Shaokun-X** [comment] 2022-07-01 08:51
@j-windsor @sivakku Hello, do you still consider adding this feature?

**Comment by IcewaveLJW** [comment] 2023-11-21 07:15
@sivakku @j-windsor Any update plan of this feature?
