### ISSUE TITLE
skaffold.yaml without default build - Cannot read property artifacts of undefined

### ISSUE THREAD

**Issue by seventieskid** [GoogleCloudPlatform/cloud-code-vscode#403] opened 2021-03-18 16:00 UTC
**Version information**

Cloud Code Extension version: 1.9.0

VSCode version: 1.54.1

OS: Mac Big Surf 11.2.2

Cloud SDK: 330.0.0

Skaffold: v1.20.0

Kubectl: v1.17.17

**Description**:

We don't want to specific any **default** build, test or deploy yaml. We want everything to fall under named profliles. Cloud Code throughs this popup error when we try to do that:-

"Cannot read property artifacts of undefined"

**Repro step**:

Cmd+Shift+P Cloud Code Run on Kuberenetes

With this skaffold.yaml it generates the error above:-

```
apiVersion: skaffold/v2beta12
kind: Config
# build:
#   artifacts:
#     - image: gcr.io/k8s-skaffold/example
profiles:
- name: consume
  deploy:
    helm:
      releases:
      - name: AnyApp
        chartPath: helm
        wait: true
```

No error for this skaffold.yaml:-

```
apiVersion: skaffold/v2beta12
kind: Config
 build:
   artifacts:
     - image: gcr.io/k8s-skaffold/example
profiles:
- name: consume
  deploy:
    helm:
      releases:
      - name: AnyApp
        chartPath: helm
        wait: true
```

This is not a skaffold issue, because this command works fine from the command line for either versions of the skaffold.yaml:-

```
$ skaffold dev -vdebug
INFO[0000] starting gRPC server on port 50051           
INFO[0000] starting gRPC HTTP server on port 50052      
INFO[0000] Skaffold &{Version:v1.20.0 ConfigVersion:skaffold/v2beta12 GitVersion: GitCommit:c48e97690d8daffd68141c2a68fcbe3df6f6936a GitTreeState:dirty BuildDate:2021-02-11T22:55:17Z GoVersion:go1.14.14 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Update check not enabled, skipping.          
INFO[0000] Loaded Skaffold defaults from "/Users/joe/.skaffold/config" 
DEBU[0000] parsed 1 configs from configuration file /Users/joe/Downloads/skaffold-issues/artifacts-not-found/skaffold.yaml 
DEBU[0000] Defaulting build type to local build         
DEBU[0000] Defaulting deploy type to kubectl            
INFO[0000] Using kubectl context: blah
DEBU[0000] Running command: [/Users/joe/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube profile list -o json] 
DEBU[0000] Running command: [/Users/joe/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube profile list -o json] 
DEBU[0000] setting Docker user agent to skaffold-v1.20.0 
DEBU[0000] Using builder: local                         
DEBU[0000] push value not present, defaulting to true because cluster.PushImages is true 
Listing files to watch...
WARN[0000] k8s/*.yaml did not match any file            
INFO[0000] List generated in 153.986µs                  
Generating tags...
INFO[0000] Tags generated in 7.38µs                     
Checking cache...
INFO[0000] Cache check completed in 41.174µs            
INFO[0000] Test completed in 743ns                      
Tags used in deployment:
DEBU[0000] getting client config for kubeContext: ``
......
```

**Comment by sivakku** [comment] 2021-03-18 16:28
Thanks for reporting. Dupe of #398, we are working on fix for this issue.

**Closed** 2021-03-18 16:46 UTC
Labels: area/skaffold
