### ISSUE TITLE
skaffold config file skaffold.yaml not found

### ISSUE THREAD

**Issue by dsaydon90** [GoogleCloudPlatform/cloud-code-vscode#379] opened 2021-02-03 17:09 UTC
**Environment**:
(Hint: "Report Extension Issue on Github" command will fill these out for you.)
Extension version: v1.8.0
VSCode version: 1.52.1
OS: ubuntu 20

**Description**:

I have configured `"skaffoldConfig": "${workspaceFolder}/Kubernetes/skaffold.yaml"` im my `launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Kubernetes: Run/Debug",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/Kubernetes/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true
        }
    ]
}
```

and I'm' getting the following issue
```
Build complete in 1.131198315s
Test complete in 605ns
Tags used in deployment:
 - myservice -> myservice:1830359bcd9a4ec062387093ab35b59c22f06163d7f71143451bb1cf85754c6c
Starting deploy...
Deploying with helm v3.5.0 ...
Helm release myservice not installed. Installing...
Building helm dependencies...
Error: error while running post render on files: error while running command /home/dors/.cache/cloud-code/installer/google-cloud-sdk/bin/skaffold. error output:
skaffold config file skaffold.yaml not found - check your current working directory, or try running `skaffold init`
: exit status 1
exiting dev mode because first deploy failed: install: exit status 1
Exited with code 1.
skaffold config file skaffold.yaml not found - check your current working directory, or try running `skaffold init`
```

**Repro step**:

create a project with the following structure
```
myservice
|_.vscode
  |_launch.json
|_ Application
  |_Dockerfile
  |_ <node js code files..>
|_Kuerbenetes
  |_skaffold.yaml
  |_ <helm chart of the myservice>
```
and with the above `launch.json` and try to run the debugger

**Comment by j-windsor** [comment] 2021-02-04 17:53
I wonder if this is the same problem as your other bug.. that skaffold is looking for your skaffold.yaml in the root of the project and it is not there. If that is the case, I believe this is working [by design](https://skaffold.dev/docs/design/config/).

Could you try placing the skaffold.yaml in your project root and see if you can repro?

**Comment by j-windsor** [comment] 2021-02-04 21:27
It looks like the problem is with Skaffold here. I have investigated and filed an issue on their repo: https://github.com/GoogleContainerTools/skaffold/issues/5355

If I got any of the details wrong, please update the issue.

**Comment by sivakku** [comment] 2021-02-18 18:26
Moving this to P3 since we are waiting for the task on skaffold side to address the depending task GoogleContainerTools/skaffold#5355.

**Comment by vincentjocodes** [comment] 2021-07-21 17:35
@dsaydon90 I hope that the Skaffold issue resolved your issue? If not, feel free to open that ticket up again. Closing this one.

**Closed by vincentjocodes** 2021-07-21 17:35 UTC
Labels: area/helm, area/skaffold, kind/bug, priority/p3
