### ISSUE TITLE
Signing in issue - Error: The authentication flow did not complete successfully, and Cloud Code for VS Code is not authorized to access your account.

### ISSUE THREAD

**Issue by gpwalczak** [GoogleCloudPlatform/cloud-code-vscode#867] opened 2023-11-23 14:40 UTC
Error: The authentication flow did not complete successfully, and Cloud Code for VS Code is not authorized to access your account.

I am failing to Sign in to Cloud Code and docs do not provide further insights beside the error message above. Does it mean the org admin disabled the access for this app for my account? How should I progress with troubleshooting to unblock from this? 

Note I have added "https://accounts.google.com" to trusted domains.

**Comment by glouischandra** [comment] 2023-12-06 21:26
Hi @gpwalczak we're currently working on rolling a fix to common authentication issue in Cloud Code, build should be live sometime next week (2.2.0). 

The error above usually means something to do with admin access or an issue fetching the exchange token from google auth server. If you still run into the issue again, please file a feedback using the in product feedback button:
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/3677364/ab71641f-0788-44f5-a0b9-f6acfd9d9b15)

And also please ensure "Send Cloud Code logs" is checked
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/3677364/2234d638-639a-4e34-8929-23deface3083)

**Comment by darkthecross** [comment] 2023-12-14 05:13
Please please please get this fixed soon. Your fellow googler just unsubscribed from copilot to try out Duet AI. 

Environment: chromebook, installed vscode as a linux app.

**Comment by glouischandra** [comment] 2023-12-14 16:06
Hi @darkthecross can you help us identify the specifics in the Cloud Code logs above? You can use the in IDE "Report a Bug / Request a Feature" form to send the logs. Thanks!

**Comment by glouischandra** [comment] 2023-12-14 18:56
Looks like this can be caused by authentication service in GCP having transient issue. If you see consistent failure please follow the above steps to send us detailed logs.

**Comment by glouischandra** [comment] 2024-10-23 18:28
This issue should be fixed in the latest version of Gemini CodeAssist extension.

**Closed as completed by glouischandra** 2024-10-23 18:28 UTC
Labels: question, area/accounts
