### ISSUE TITLE
Add a way to create resources from the command palette

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#187] opened 2020-01-09 23:09 UTC
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

Right now the best way I've found to create a resource, let's say a configmap is to first open a new file, save it as yaml, then know that the snippet menu is Ctrl-Space, then type configmap, then type enter and I got a snippet ready.

Could it be possible to have straight from the command palette the possibility to type "Create configmap" and having a new tab showing with a snippet ready to be edited? This could be of course made available for the base object of Kubernetes but also for other extensions.

**Comment by jmah-cc** [comment] 2020-12-07 21:18
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3758)

**Comment by jmah-cc** [comment] 2021-04-12 20:20
Dupe of #178 https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/178 (tracking this as a part of overall explorer improvement work)

**Closed by jmah-cc** 2021-04-12 20:20 UTC
Labels: backlog, kind/enhancement
