### ISSUE TITLE
Cannot configure container image build preferences

### ISSUE THREAD

**Issue by DecisionSystems** [GoogleCloudPlatform/cloud-code-vscode#281] opened 2020-08-20 16:18 UTC
Expected Behavior
Following instructions on this page: https://cloud.google.com/code/docs/intellij/image-build-settings
I have an existing application.

Actual Behavior
Nothing happens when I do this:

Navigate to the Run/Debug configurations dialog on the top taskbar or the top-level main menu: Run > Edit Configurations... > Develop on Kubernetes or Run on Kubernetes and choose the Build/Deploy tab.

Additional Information
Running MiniKube / Hyper-V for storing Docker and MiniKube objects

IDE type (e.g. IntelliJ, Pycharm): Visual Studio Code

IDE version: Version 1.48.0

Cloud Code version (Settings > Plugins > Cloud Code): Version 1.5.0

Cloud SDK (Settings > Cloud Code > Cloud SDK)

Are you allowing the plugin to manage the Cloud SDK:
Version of the Cloud SDK:
Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): Yes

Operating System: Windows 10 Enterprise build 2004

I also manually installed skaffold after this, but still nothing.

I also have MS Kubernetes Plugin + IBM Developer Tools running.
Using Docker with Hyper-V

**Comment by jmah-cc** [comment] 2020-08-25 19:19
Dupe of #283

**Closed by jmah-cc** 2020-08-25 19:19 UTC
