### ISSUE TITLE
Docker was found in the path, but does not appear to be running

### ISSUE THREAD

**Issue by simonyarde** [GoogleCloudPlatform/cloud-code-vscode#419] opened 2021-04-19 11:16 UTC
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: v1.10.0

VSCode version: Version: 1.55.2

OS: macOS 10.15.7 (19H524)

Cloud SDK: Google Cloud SDK 336.0.0

Skaffold: v1.21.0

Kubectl: v1.19.7

**Description**: 

"Docker was found in the path, but does not appear to be running. Please start the Docker daemon and try again."

Docker Desktop reports that Docker is running.

Docker Desktop was installed prior to installing plugin.

**Repro step**:

**Comment by kschaab** [comment] 2021-04-19 15:02
Hi @simonyarde , would you mind running docker info in the VS Code terminal window and see what is returned and does $? == 0?

**Comment by simonyarde** [comment] 2021-04-19 15:36
Hi @kschaab. Switching into default context allowed the deployment to proceed. Thanks! It didn't occur to me to check the context from the error.

```
$ docker info
Command "info" not available in current context (aci), you can use the "default" context to run this command
$ echo $?
1
$ docker context show
aci
$ docker context use default
default
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)
  ...
```

**Comment by kschaab** [comment] 2021-04-19 18:39
@simonyarde great, seems like we should fix this!

**Comment by kschaab** [comment] 2021-04-19 18:41
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4461)

**Comment by simonyarde** [comment] 2021-04-20 09:04
Thanks @kschaab. Sounds like a really helpful improvement!

**Comment by sivakku** [comment] 2021-04-23 15:42
We are working on improving the error message to add more details form docker info for troubleshooting, should be in the next release.

**Comment by quoctruong** [comment] 2021-04-28 20:00
The issue is addressed in the new release. Please give it a try.

**Closed by quoctruong** 2021-04-28 20:00 UTC
Labels: area/kubernetes, in-next-release, kind/bug, priority/p1

**Comment by ikogan** [comment] 2021-06-22 20:55
I'm getting this on Linux trying to run Cloud Code in a dev container. `docker inspect` shows:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 50
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-55-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.33GiB
 Name: 
 ID: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: user
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

The return code is `0` and the context is `default`. Should I open another issue for this? The extension version is 1.12.1.
