### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by DecisionSystems** [GoogleCloudPlatform/cloud-code-vscode#284] opened 2020-08-20 20:01 UTC
- Issue Type: `Bug`
- Extension Name: `cloudcode`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 373,
		"activateCallTime": 3,
		"activateResolvedTime": 23977,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "googlecloudtools.cloudcode",
				"_lower": "googlecloudtools.cloudcode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Failed to configure docker authentication, Jib builds may fail to push to Google Container Registries as a result.  Error: Traceback (most recent call last):\r\n  File \"C:\\Users\\rkarabush\\AppData\\Local\\cloud-code\\installer\\google-cloud-sdk\\bin\\..\\lib\\gcloud.py\", line 20, in <module>\r\n    from __future__ import absolute_import\r\nImportError: cannot import name absolute_import\r\n"
		}
	]
}
```

**Comment by jmah-cc** [comment] 2020-08-25 19:19
Dupe of #283

**Closed by jmah-cc** 2020-08-25 19:19 UTC
