### ISSUE TITLE
Can't install dependencies on remote dev containers

### ISSUE THREAD

**Issue by mihaiaperghis** [GoogleCloudPlatform/cloud-code-vscode#530] opened 2022-02-15 00:31 UTC
Issue Type: <b>Bug</b>

It seems that attempting to install the extension within a remote Python development container fails to install any dependencies. The error provided is:

> Cloud SDK was installed but was found to be invalid or corrupted so it was removed. Attempting to reinstall. Managed dependencies will be unavailable during this process. (install attempt 3)

The container is the standard one created by the [ms-vscode-remote.remote-containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension for Python, without node installed.

The container is connected to a WSL2 Ubuntu folder that has the source code. Installing the extension directly on WSL2 works fine (even tested creating a Cloud Run application from the source code). However, regardless of whether the extension in installed on WSL, it will keep failing within the remote container.

*Context*
- Managed Dependencies: on
- Cloud SDK Version: Not installed
- Skaffold Version: Not installed
- Minikube Version: Not installed

Extension version: 1.17.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3700)|
|Memory (System)|31.32GB (19.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3700)|
|Memory (System)|31.32GB (19.57GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30438033
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438167
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by kschaab** [comment] 2022-02-22 22:55
If the dev container yours is based off is public would you mind sharing the repo link?  We are unable to reproduce with public python dev container.

**Comment by ssmall** [comment] 2022-03-04 23:02
Hi @mihaiaperghis,

I am going to close this issue for now as we have been unable to reproduce. If you are still experiencing this issue, please feel free to re-open with more details about how your Python remote dev container is configured so that we can attempt to reproduce this issue.

**Closed by ssmall** 2022-03-04 23:02 UTC
Labels: question

**Comment by mihaiaperghis** [comment] 2022-03-07 08:46
It's odd, seems that after rebooting the machine the extension started to work with no other errors. I'll reopen this if I run into the same issue again.
