### ISSUE TITLE
$HOME differs between local debugger and real Cloud Run

### ISSUE THREAD

**Issue by sorenisanerd** [GoogleCloudPlatform/cloud-code-vscode#412] opened 2021-04-07 21:05 UTC
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 335.0.0
- Skaffold Version: v1.21.0
- Minikube Version: 1.18.1

On Cloud Run $HOME is /root, but in the local debugger it is /home.

Extension version: 1.10.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 3899)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 2|
|Memory (System)|15.57GB (0.88GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 426aaa54-65ae-4f77-81a7-939c4a89e129|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by sivakku** [comment] 2021-04-08 16:24
@sorenisanerd - Thanks for the feedback. Can you explain how the difference affects your tooling flow or service? The actual mapping of $HOME depends on the platform and it is probably good not to depend what the actual directory path it maps to.

**Comment by sorenisanerd** [comment] 2021-04-08 18:45
I'm deploying an app that looks in $HOME for a file. I've resorted to copying it to both /root and /home in my Dockerfile.

I don't understand what you mean it'll depend on the platform? I'm doing both debugging and deployment from VSCode. If I can't expect them to be (very, very close to) identical, than what good is the debugger?

**Comment by quoctruong** [comment] 2021-05-03 17:17
@sorenisanerd Does the file in $HOME get deployed to Cloud Run as well?

**Comment by sorenisanerd** [comment] 2021-05-03 18:39
Yes.

**Comment by quoctruong** [comment] 2021-05-03 22:54
Is it possible to share the application and the `Dockerfile`?

**Comment by vincentjocodes** [comment] 2021-05-18 20:20
@sorenisanerd Just wanted to follow up here to see if we could get a sample Dockerfile and an simple app sample of what you are describing so that we could more deeply look into this issue? Thank you.

**Comment by sorenisanerd** [comment] 2021-05-24 03:44
https://gist.github.com/sorenisanerd/60587123e7bf9221d8719c11bc68cc23

**Comment by j-windsor** [comment] 2021-05-24 21:21
@sorenisanerd interestingly enough, I cannot repro with the gist you provided. When I use Cloud Run Emulator, I see that `$HOME` is `/root`. I see this both on macOS and Debian linux. Is there any special configuration in docker that you are using?

<img width="1792" alt="Screen Shot 2021-05-24 at 4 58 40 PM" src="https://user-images.githubusercontent.com/554839/119408882-7354bb00-bcb4-11eb-80d7-8f7654002fdf.png">

**Comment by j-windsor** [comment] 2021-05-24 21:32
@sorenisanerd interestingly enough, I cannot repro with the gist you provided. When I use Cloud Run Emulator, I see that `$HOME` is `/root`. I see this both on macOS and Debian linux. Is there any special configuration in docker that you are using?

<img width="1792" alt="Screen Shot 2021-05-24 at 4 58 40 PM" src="https://user-images.githubusercontent.com/554839/119409934-09d5ac00-bcb6-11eb-80e9-cf354e0a57eb.png">

**Comment by sorenisanerd** [comment] 2021-05-24 22:01
@j-windsor That's exactly the problem I'm trying to point out. If you run it on Google Cloud Run, $HOME is `/home`, not `/root`.

**Comment by j-windsor** [comment] 2021-05-26 14:29
Ahh I see now. Thanks for the great repro! We are talking to Cloud Run to determine a good solution for this. Thanks for reporting!

**Comment by sorenisanerd** [comment] 2021-05-26 14:30
Sure! Thanks for looking into it.

**Comment by sivakku** [comment] 2021-06-01 17:54
Thanks for the repro @sorenisanerd. Cloud Run is trying to rollout a fix for this one, i will get back once their timelines are finalized. 
---- Internal tracking bug if any googlers are going over it 154368323 -----

**Comment by sivakku** [comment] 2021-09-13 23:06
The issue is still getting rolled out to Cloud Run clusters as an experiment and is still pending.

**Comment by kschaab** [comment] 2022-11-16 17:43
This is rolled out.

**Closed by kschaab** 2022-11-16 17:43 UTC
Labels: kind/enhancement, priority/p2, area/cloudrun
