### ISSUE TITLE
Managed Dependencies not available on Windows 11 ARM64 

### ISSUE THREAD

**Issue by sspage** [GoogleCloudPlatform/cloud-code-vscode#967] opened 2024-11-28 20:02 UTC
**Environment**:
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT arm64 10.0.26120

**Version information**

Cloud Code Extension version:
v2.21.0

VSCode version:
Version: 1.95.3 (user setup)

OS: 
OS: Windows_NT arm64 10.0.26120

Cloud SDK:
Google Cloud SDK 502.0.0
bq 2.1.9
core 2024.11.15
gcloud-crc32c 1.0.0
gsutil 5.31

Skaffold: 

Kubectl:

**Description**:
Managed dependencies are currently unavailable due to failure.  Cloud Code will reattempt to install managed dependencies after Visual Studio Code is restarted. Failed to install Cloud SDK. Unsupported architecture: win32/arm64

Source:  Gemini Code Assist + Google Cloud Code

Cloud SDK was installed but was found to be invalid or corrupted so it was removed. Attempting to reinstall. Managed dependencies will be unavailable during this process. (install attempt 3)

**Repro step**:
Install Google Cloud SDK on ARM from public website.  
Install Gemini Extension
Open VSCode.  Messages are at VSCode Startup.

**Comment by kschaab** [comment] 2024-12-05 14:55
This will be fixed in the next release of Cloud Code.

**Comment by kschaab** [comment] 2024-12-05 14:56
Duplicate of #963

**Closed as not planned** 2024-12-05 14:57 UTC
