### ISSUE TITLE
001

### ISSUE THREAD

**Issue by Theking20s** [GoogleCloudPlatform/cloud-code-vscode#950] opened 2024-10-23 01:10 UTC
**Use case**
What are you trying to do that our extension doesn't let you?
Eg, I want to deploy frequently to manually test my code change.
Running deploy command every time is annoying.

**Feature**
What would help?
Eg, Maybe a continuous deploy command?

**Comment by maxrandolph** [comment] 2024-10-30 20:19
closing as duplicate of https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/951

**Closed as completed by maxrandolph** 2024-10-30 20:19 UTC
Labels: duplicate
