### ISSUE TITLE
Errors on WSL. UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory settings.json

### ISSUE THREAD

**Issue by Yggdrasil** [GoogleCloudPlatform/cloud-code-vscode#174] opened 2019-12-18 15:39 UTC
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.0
OS: linux (Ubuntu 18.04 in WSLv1, Windows 10 1909)

**Description**:
Whenever I open a project via Remote WSL I get the below errors. This only occurs in WSL.

When I reopen the same project in Windows there are no errors. Opening a new blank window in WSL also does not show any errors.

It seems obvious that paths like `c:/Users/martijn/AppData/` aren't reachable from within WSL, but I don't know enough about vscode or the extention to know how to resolve the errors.

```
[Trace - 2:00:07 PM] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}

[Trace - 2:00:07 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "vscode-local:/c%3A/Users/martijn/AppData/Roaming/Code/User/settings.json",
            "type": 2
        },
        {
            "uri": "vscode-userdata:/c%3A/Users/martijn/AppData/Roaming/Code/User/settings.json",
            "type": 2
        }
    ]
}

[Trace - 2:00:07 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "(node:14959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:/Users/martijn/AppData/Roaming/Code/User/settings.json'"
}

[Error - 2:00:07 PM] (node:14959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:/Users/martijn/AppData/Roaming/Code/User/settings.json'
[Trace - 2:00:07 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "(node:14959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)"
}

[Error - 2:00:07 PM] (node:14959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Trace - 2:00:07 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "(node:14959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:/Users/martijn/AppData/Roaming/Code/User/settings.json'"
}

[Error - 2:00:07 PM] (node:14959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:/Users/martijn/AppData/Roaming/Code/User/settings.json'
[Trace - 2:00:07 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "(node:14959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)"
}

[Error - 2:00:07 PM] (node:14959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Repro step**:
On Windows 10 1909, activate WSL and install and configure the Ubuntu 18.04 distro.
In vscode, install the Remote-WSL extension and open a project in WSL. Install the Cloud Code extension and start working on files.

**Comment by kschaab** [comment] 2019-12-18 16:42
Thanks, this is fixed in our upcoming release.

Duplicate of #171

**Closed** 2019-12-18 16:42 UTC
