### ISSUE TITLE
Cloud run emulator not working on Mac M1, it seems bug.

### ISSUE THREAD

**Issue by codecycletechnologies** [GoogleCloudPlatform/cloud-code-vscode#389] opened 2021-02-24 10:58 UTC
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.8.0
VSCode version: 1.53.2
OS: Mac OS M1

**Description**:
Getting below error while performing "Cloud Code: Run on cloud run emulator" command from vscode. 

stderr:SIGSEGV: segmentation violationPC=0x0 m=0 sigcode=0
Process exited with status 139 from signal SEGV

![Screenshot 2021-02-24 at 2 20 00 PM](https://user-images.githubusercontent.com/77831707/108990526-fc138900-76bc-11eb-9b91-25eb63d5933b.png)

**Repro step**:

**Comment by codecycletechnologies** [comment] 2021-02-24 12:07
@j-windsor and @vincentjocodes Can you please look into this?

**Comment by sivakku** [comment] 2021-02-24 20:45
> @j-windsor and @vincentjocodes Can you please look into this?

@codecycletechnologies - We are working on an insider build that works on M1, stay tuned for updates on the build. Please use #390 as master task for when it is available.

**Comment by codecycletechnologies** [comment] 2021-02-25 07:30
@sivakku Thank you for the update. Looking forward for the fix!

**Comment by sivakku** [comment] 2021-03-01 17:28
Thanks @codecycletechnologies, i will close this one since we can use the master task to track about progress and updates.

**Comment by medyagh** [comment] 2021-03-11 19:49
any chance to know what version of minikube was used ?

**Comment by kschaab** [comment] 2021-03-11 19:52
The screen shots show v1.20.2

**Comment by medyagh** [comment] 2021-03-11 19:54
> The screen shots show v1.20.2

1.20.2 is the kuberntes version

latest minikube version is 1.18.1

**Comment by ilya-zuyev** [comment] 2021-03-11 21:23
Looks like it's https://github.com/kubernetes/minikube/issues/10310
@codecycletechnologies what version of M1 Docker For Desktop are you using? If it's lower than preview-3.1.0  do you mind updating it please?

**Comment by codecycletechnologies** [comment] 2021-03-24 09:13
@ilya-zuyev I have upgraded preview to 3.3.0 version and tried to execute emulator but getting error as attached.

![Screenshot 2021-03-24 at 2 42 38 PM](https://user-images.githubusercontent.com/77831707/112284483-4d5c6b80-8caf-11eb-9368-6c1959371844.png)

**Comment by sivakku** [comment] 2021-03-30 21:40
> @ilya-zuyev I have upgraded preview to 3.3.0 version and tried to execute emulator but getting error as attached.
> 
> ![Screenshot 2021-03-24 at 2 42 38 PM](https://user-images.githubusercontent.com/77831707/112284483-4d5c6b80-8caf-11eb-9368-6c1959371844.png)

@ilya-zuyev/@medyagh - Can you look at this error message?

**Comment by ilya-zuyev** [comment] 2021-04-05 22:29
@sivakku could you double check that you're using `arm64` version of minikube and not 'amd64`?

**Comment by codecycletechnologies** [comment] 2021-04-15 05:01
@ilya-zuyev Hi, I tried to run minikube version command and received only version.

```
minikube version
minikube version: v1.17.1
```

Can you please let us know how to verify processor of minikube?

**Comment by codecycletechnologies** [comment] 2021-04-16 05:35
Hello @ilya-zuyev,
I have reinstalled amd64 minikube and tried to run cloud run emulator again.  But still receiving same error.

Below are my configurations
minikube - v1.19.0 amd64
docker - 20.10.5
docker desktop - 3.3.1

**Comment by codecycletechnologies** [comment] 2021-04-23 04:06
@ilya-zuyev any updates?

**Comment by sivakku** [comment] 2021-05-07 17:28
@codecycletechnologies - Can you go back to arm64 version as ilya mentioned? You need to replace minikube with the file location to get the arch version of it.

**Comment by beingminimal** [comment] 2021-05-11 07:22
@sivakku and @ilya-zuyev , Thanks for the detail.

We tried to run file minikube command from terminal and receiving below repsonse.
```
codecycle@Codecycles-Mac-mini ~ % file minikube
minikube: cannot open `minikube' (No such file or directory)
```

Also I tried to run Cloud run emulator again and now receiving below error
```
Dependency check started
Dependency check succeeded
Starting minikube, this may take a while.
Failed to start minikube: X Exiting due to MK_WRONG_BINARY_M1: You are trying to run amd64 binary on M1 system. Please use darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.19.0/minikube-darwin-amd64.)
```

I have deleted minikube from PC and downloaded arm64 and installed through with curl.  Retried running emulator from extension but we are receiving same error as above.

I tried to run `minikube start` command from terminal and it shows `minikube v1.20.0 on Darwin 11.3.1 (arm64) `
```
codecycle@Codecycles-Mac-mini ~ % minikube start
😄  minikube v1.20.0 on Darwin 11.3.1 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
```

**Comment by codecycletechnologies** [comment] 2021-05-11 07:23
@sivakku and @ilya-zuyev , Thanks for the detail.

We tried to run file minikube command from terminal and receiving below response.

codecycle@Codecycles-Mac-mini ~ % file minikube
minikube: cannot open `minikube' (No such file or directory)
Also I tried to run Cloud run emulator again and now receiving below error

Dependency check started
Dependency check succeeded
Starting minikube, this may take a while.
Failed to start minikube: X Exiting due to MK_WRONG_BINARY_M1: You are trying to run amd64 binary on M1 system. Please use darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.19.0/minikube-darwin-amd64.)
I have deleted minikube from PC and downloaded arm64 and installed through with curl. Retried running emulator from extension but we are receiving same error as above.

I tried to run minikube start command from terminal and it shows minikube v1.20.0 on Darwin 11.3.1 (arm64)

codecycle@Codecycles-Mac-mini ~ % minikube start
😄  minikube v1.20.0 on Darwin 11.3.1 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...

**Comment by sivakku** [comment] 2021-05-11 19:26
@codecycletechnologies 

1. Let's figure out the location of Minikube you are using on M1: Do you have auto dependencies turned ON in VSCode? if so you are using the version of minikube code VSCode installs in the private path. Check the below setting to check, if it says 'ON' it will be `/Users/<username>/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/minikube` on the M1. if 'OFF' then it is using the one you installed in your system PATH.
![image](https://user-images.githubusercontent.com/16199637/117872217-484d7e80-b253-11eb-8e64-f8151595ce44.png)

2. Do a file version on the full path of where Minikube is located to know what architecture it is using.
```
$ file /Users/<username>/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/minikube
/Users/<username>/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube: Mach-O 64-bit executable x86_64
```
3. If you have the setting ON, then VSCode installs the right architecture for you. If it is in a messed up state just delete the directory `/Users/<user-name>/Library/Application\ Support/cloud-code/installer` and restart vscode then it will re-install all dependencies needed.

**Comment by codecycletechnologies** [comment] 2021-05-12 04:55
@sivakku Thanks for all the steps..

Yes, vscode settings was turned ON and I verified file version on my path shows
`/Users/<username>/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube: Mach-O 64-bit executable x86_64`

Even after deleting folder and letting vscode install dependency automatically,  I am receiving `MK_WRONG_BINARY_M1: You are trying to run amd64 binary or stderr:SIGSEGV: segmentation violationPC=0x0 m=0 sigcode=0` error.

**Comment by j-windsor** [comment] 2021-05-14 20:35
It looks like our dependency manager is retrieving the wrong version of minikube. Can you please provide the following information to help us debug?
1. Your current version of Cloud Code
2. Result of `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud info` (feel free to sanitize if needed).
3. Result of
```
file `which python3`
```
4. Result of
```
file `which python`
```

Thanks! I suspect that if your Cloud Code is up to date, the wrong version is getting installed because you have an x86 version of python installed, so our python based installer sees x86 as your arch.

**Comment by sivakku** [comment] 2021-05-14 20:49
@codecycletechnologies - i can reproduce this on M1, i see it was a result of having amd64 python installed in the system PATH that resulted in gcloud installing amd64 version of minikube instead of installing arm64. Here are the steps to confirm if that is the case you are running in to and steps to get arm64 version of minikube.

1. Check if the system path has amd64 version of Python, if the machine field says 'x86_64' then you would need to install arm64 version of python on your box.

```
>>> import os; os.uname()
posix.uname_result(sysname='Darwin', nodename='', release='20.1.0', version='Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE...', **machine='x86_64'**)
```

2. Install arm64 version of python: following this tutorial that uses arm64 [homebrew](https://smarttechnicalworld.com/how-to-install-homebrew-on-mac-m1/) to get arm64 version of python installed. Verify that your path contains and uses python and python3 of arm64 version. The brew doesn't update PATH for python link to arm64, you would need put this in to the path through bash_profile(if you are using bash) and that's ahead of other pythons you have on the box.

```
$ echo $PATH
**/opt/homebrew/opt/python@3.9/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin**:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sivakumarkalva/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin
```
 
3. Check to make sure you have arm64 python in your system path.

```
$ which python
/opt/homebrew/opt/python@3.9/libexec/bin/python
```
```
>>> import os; os.uname()
posix.uname_result(sysname='Darwin', nodename='sivas-Air.home', release='20.1.0', version='Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101', **machine='arm64'**)
```

4. Go to VSCode terminal, delete the private dependencies under this location, so it would re-install the gcloud and minikube. Restart VSCode after deleting the directory

```
rm -rf /Users/<user-name>/Library/Application\ Support/cloud-code/installer
```

5. At the bottom right after restart you would see "installing cloud code dependencies..", let it finish and this time you can verify that you have arm64 version of minikube installed.

```
$ file /Users/<username>/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/minikube
/Users/<username>/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube: Mach-O 64-bit executable **arm64**
```

6. So far it confirms that you got the right arm64 version of minikube, if for some reason it still fails and you have right version of python, just run these two additional commands(not needed, just a backup).

```
gcloud components remove minikube
gcloud components install minikube
```

**Comment by codecycletechnologies** [comment] 2021-05-15 05:11
> It looks like our dependency manager is retrieving the wrong version of minikube. Can you please provide the following information to help us debug?
> 
> 1. Your current version of Cloud Code
**1.11.1**


> 2. Result of `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud info` (feel free to sanitize if needed).
```
Google Cloud SDK [340.0.0]

Platform: [Mac OS X, x86_64] uname_result(system='Darwin', node='Codecycles-Mac-mini.local', release='20.4.0', version='Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101', machine='x86_64', processor='i386')
Locale: ('en_GB', 'UTF-8')
Python Version: [3.8.2 (default, Apr  8 2021, 23:19:18)  [Clang 12.0.5 (clang-1205.0.22.9)]]
Python Location: [/Library/Developer/CommandLineTools/usr/bin/python3]
Site Packages: [Disabled]

Installation Root: [/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk]
Installed Components:
  gsutil: [4.61]
  core: [2021.05.07]
  bq: [2.0.67]
  kubectl: [1.17.17]
  alpha: [2021.05.07]
  minikube: [1.18.1]
  beta: [2021.05.07]
  skaffold: [1.20.0]
System PATH: [/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin]
Python PATH: [/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party:/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8:/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload]
Cloud SDK on PATH: [True]
Kubectl on PATH: [/usr/local/bin/kubectl]

WARNING: There are other instances of the Google Cloud Platform tools on your system PATH.
  /Applications/Docker.app/Contents/Resources/bin/kubectl

Installation Properties: [/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/properties]
User Config Directory: [/Users/codecycle/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/Users/codecycle/.config/gcloud/configurations/config_default]

Account: [XXXX]
Project: [None]

Current Properties:
  [core]
    account: [XXXX]
    disable_usage_reporting: [True]

Logs Directory: [/Users/codecycle/.config/gcloud/logs]
Last Log File: [/Users/codecycle/.config/gcloud/logs/2021.05.15/10.25.26.752229.log]

git: [git version 2.31.1]
```



> 3. Result of
> 
> ```
> file `which python3`
> ```
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):     Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):     Mach-O 64-bit executable arm64e

> 1. Result of
> 
> ```
> file `which python`
> ```
/usr/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python (for architecture x86_64):      Mach-O 64-bit executable x86_64
/usr/bin/python (for architecture arm64e):      Mach-O 64-bit executable arm64e
> 
> Thanks! I suspect that if your Cloud Code is up to date, the wrong version is getting installed because you have an x86 version of python installed, so our python based installer sees x86 as your arch.


Please have a look at above configurations and let us know how and through which command we need to make changes in system. Thanks!

**Comment by codecycletechnologies** [comment] 2021-05-15 05:19
> @codecycletechnologies - i can reproduce this on M1, i see it was a result of having amd64 python installed in the system PATH that resulted in gcloud installing amd64 version of minikube instead of installing arm64. Here are the steps to confirm if that is the case you are running in to and steps to get arm64 version of minikube.
> 
> 1. Check if the system path has amd64 version of Python, if the machine field says 'x86_64' then you would need to install arm64 version of python on your box.
> 

I am not sure where and how to run below lines of code. Can you please provide command to get below kind of response.
> ```
> >>> import os; os.uname()
> posix.uname_result(sysname='Darwin', nodename='', release='20.1.0', version='Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE...', **machine='x86_64'**)
> ```
> 
> 1. Install arm64 version of python: following this tutorial that uses arm64 [homebrew](https://smarttechnicalworld.com/how-to-install-homebrew-on-mac-m1/) to get arm64 version of python installed. Verify that your path contains and uses python and python3 of arm64 version. The brew doesn't update PATH for python link to arm64, you would need put this in to the path through bash_profile(if you are using bash) and that's ahead of other pythons you have on the box.
> 
> ```
> $ echo $PATH
> **/opt/homebrew/opt/python@3.9/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin**:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sivakumarkalva/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin
> ```
> 

Can you please check configurations provided in https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/389#issuecomment-841602346. Path shows python installation in CommandLineTools. So should we delete that and reinstall it through homebrew?  

Rest  of the  steps we can  perform after having correct version of python with proper  PATH.

**Comment by sivakku** [comment] 2021-05-17 15:52
> > @codecycletechnologies - i can reproduce this on M1, i see it was a result of having amd64 python installed in the system PATH that resulted in gcloud installing amd64 version of minikube instead of installing arm64. Here are the steps to confirm if that is the case you are running in to and steps to get arm64 version of minikube.
> > 
> > 1. Check if the system path has amd64 version of Python, if the machine field says 'x86_64' then you would need to install arm64 version of python on your box.
> 
> I am not sure where and how to run below lines of code. Can you please provide command to get below kind of response.
> 
> > ```
> > >>> import os; os.uname()
> > posix.uname_result(sysname='Darwin', nodename='', release='20.1.0', version='Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE...', **machine='x86_64'**)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Install arm64 version of python: following this tutorial that uses arm64 [homebrew](https://smarttechnicalworld.com/how-to-install-homebrew-on-mac-m1/) to get arm64 version of python installed. Verify that your path contains and uses python and python3 of arm64 version. The brew doesn't update PATH for python link to arm64, you would need put this in to the path through bash_profile(if you are using bash) and that's ahead of other pythons you have on the box.
> > 
> > ```
> > $ echo $PATH
> > **/opt/homebrew/opt/python@3.9/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin**:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sivakumarkalva/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin
> > ```
> 
> Can you please check configurations provided in [#389 (comment)](https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/389#issuecomment-841602346). Path shows python installation in CommandLineTools. So should we delete that and reinstall it through homebrew?
> 
> Rest of the steps we can perform after having correct version of python with proper PATH.

In the python interpreter on a command line to see what architecture it is picking up. Even though the /usr/bin/python3 has both, the python picks up amd64 over arm64.

```
$ python
>>> import os; os.uname()
```

**Comment by codecycletechnologies** [comment] 2021-05-18 04:32
@sivakku Hey thanks for the detail
Here is my output of given script.

>>> import os;os.uname()
('Darwin', 'Codecycles-Mac-mini.local', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101', 'arm64')

**Comment by sivakku** [comment] 2021-05-18 14:01
> @sivakku Hey thanks for the detail
> Here is my output of given script.
> 
> > > > import os;os.uname()
> > > > ('Darwin', 'Codecycles-Mac-mini.local', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101', 'arm64')

Ok, that verifies you have right version of python. Where is your VSCode(code) located? Downloads or Applications directory. if it is in Downloads directory move it to Applications, it doesn't resolve arm64 binaries if it is in Downloads directory.

**Comment by codecycletechnologies** [comment] 2021-05-19 04:18
@sivakku ,

VS code is inside application directory.

**Comment by sivakku** [comment] 2021-05-19 15:37
> @sivakku ,
> 
> VS code is inside application directory.

Ok, Did you try steps 4, 5, 6 from the [comment](https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/389#issuecomment-841496665)? and Can you paste the output of it as well?

**Comment by codecycletechnologies** [comment] 2021-05-20 05:50
@sivakku , Yes I ran 4th and 5th step and still it is taking wrong minikube version
```
codecycle@Codecycles-Mac-mini ~ % file /Users/codecycle/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/minikube 
/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube: Mach-O 64-bit executable x86_64
```
After that tried to run 6th step
```
gcloud components remove minikube
gcloud components install minikube
```
Even after running 4, 5, and 6 step my file command doesnt shows arm64 version of minikube
```
codecycle@Codecycles-Mac-mini ~ % file /Users/codecycle/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/minikube
/Users/codecycle/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube: Mach-O 64-bit executable x86_64
```

**Comment by sivakku** [comment] 2021-06-25 16:57
@codecycletechnologies - i am not sure what is happening on your M1, a reproducible steps here might help to reproduce on our end. if you still have the problem and still not installing right architecture of minikube onM1 then please do reach out on [cloud code slack channel](https://join.slack.com/t/googlecloud-community/shared_invite/zt-erdf4ity-8ZMUQ18DYV~5hkbZ~gCswg), then we should be able to troubleshoot and would be happy to setup a meet(video) to go over it as well if that makes it easier.

**Closed by sivakku** 2021-06-25 16:57 UTC
Labels: area/arm64, question
