### ISSUE TITLE
Cannot log in to Google Cloud SDK

### ISSUE THREAD

**Issue by goncalovf** [GoogleCloudPlatform/cloud-code-vscode#310] opened 2020-10-07 16:18 UTC
When clicking on the "Open with Cloud Code" button on [Quickstart for remote development](https://cloud.google.com/code/docs/vscode/quickstart-remote-dev) quickstart guide, Visual Studio Code (VSC) gives me the error: `Error: need to login to use Cloud Shell`.

On VSC, when I click on "Click here to log in to Google Cloud SDK" in the "Cloud Code - Kubernetes" menu (in left side activity bar), under "Google Kubernetes Engine Explorer", I get the following error:

```
'""C:\Users\gonca\AppData\Local\Google\Cloud' is not recognized as an internal o
r external command,
operable program or batch file.
'""C:\Users\gonca\AppData\Local\Google\Cloud' is not recognized as an internal o
r external command,
operable program or batch file.
ERROR: gcloud failed to load: cannot import name 'exceptions' from 'apitools.bas
e.py' (unknown location)
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util      
    from apitools.base.py import exceptions as apitools_exceptions

This usually indicates corruption in your gcloud installation or problems with y
our Python interpreter.

Please verify that the following is the path to a working Python 2.7 or 3.5+ exe
cutable:
    C:\Users\gonca\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bund
ledpython\python.exe

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a 
working Python 2.7 or 3.5+ executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the
 instructions here:
    https://cloud.google.com/sdk/

Press any key to exit.
```

I can't seem to find the issue. I have a GCP project that I can access to with `gcloud` and `kubectl` with Google Cloud SDK.

### CONFIGURATION

**PATH**
In PATH I have:
- kubectl (in `...\Google\Cloud SDK\google-cloud-sdk\bin`)
- Python 3.7.5 (in `...\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython`)
- Skaffold (in `C:\ProgramData\chocolatey\bin`)

I tried using Python 2.7.13 by setting `CLOUDSDK_PYTHON` environment variable to point to `...\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython2\python.exe`

I've also tried uninstalling and reinstalling Google Cloud SDK several times.

**Visual Studio Code**
Extensions installed:
- Cloud Code 1.6.0
- Debugger for Java 0.28.0
- Go 0.17.2
- Python 2020.9.114305
- Remote - SSH 0.55.0
- Remote - SSH: Editing Configuration Files 0.55.0
- Remote - WSL 0.44.5

**gcloud version**
Output of `gcloud version` (from Command Prompt):
- Google Cloud SDK 313.0.0
- bq 2.0.61
- core 2020.10.02
- gsutil 4.53
- kubectl 1.15.11

**Other**
I have:
- Windows 10 Pro 64-bit (10.0, Build 19041)
- Docker Desktop 2.4.0.0 (48506).

### Related Issues
This issue seems similar to #64. I tried opening Visual Studio from the Command Prompt with `start code` but didn't change the outcome.

**Comment by sivakku** [comment] 2020-10-08 18:10
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3332)

**Comment by j-windsor** [comment] 2020-10-12 16:43
Hmm...

Could you please verify for us that the vscode `cloudcode.autoDependencies` setting is set to `off`? Based on what you said it sounds like you have opted out of automatic dependency management, but just making sure.

<img width="751" alt="Screen Shot 2020-10-12 at 9 41 48 AM" src="https://user-images.githubusercontent.com/554839/95771057-43016480-0c6f-11eb-988e-09c8dc471ed3.png">

**Comment by goncalovf** [comment] 2020-10-12 20:17
The vscode `cloudcode.autoDependencies` setting is set to `on`, exactly as in your printscreen. I didn't make any change to the default settings.

**Comment by kschaab** [comment] 2020-10-15 17:41
@goncalovf there is a patch release to 1.6.1 which we believe will fix the issue inside VS Code.  I'm not sure that will do much for the errors for gcloud on the command line though, does `gcloud auth login` work in the installed version of gcloud?  It might be beneficial to wipe this and reinstall the CLI if that fails and you depend on the command line version working.

**Comment by goncalovf** [comment] 2020-10-16 19:34
Unfortunately, the issue is still occurring. Steps I took:

1. Uninstall the Cloud Code extension on vscode and re-install it (version 1.6.1).
2. Run `google auth login` on Google Cloud SDK and successfully authenticated.
3. Installed updates for Cloud SDK components with `gcloud components update`
4. Checked vscode and still the same issue occurred when trying to log in.
5. Uninstall Cloud SDK and re-install it. Configure it with `gcloud init`.
6. Steps 2 and 4 again. Issue persists.

**Comment by goncalovf** [comment] 2020-10-27 07:44
Any update on this?

**Comment by kschaab** [comment] 2020-12-01 18:01
Sorry, we missed your feedback.  There is a way to work around this issue per #332.  While we haven't identified the underlying cause for this issue we can automatically recover in a future release.

**Comment by goncalovf** [comment] 2020-12-02 11:40
Thanks @kschaab, the work-around works! I was able to login to GKE.

**Comment by sivakku** [comment] 2020-12-09 23:03
We will be releasing a fix at the next version to detect the auto installer corruption and fix the cloud sdk.

**Comment by sivakku** [comment] 2021-01-08 17:25
Duplicate of #346

**Closed by sivakku** 2021-01-08 17:25 UTC
Labels: in-next-release, kind/bug, priority/p1
