### ISSUE TITLE
Installed Google Cloud SDK  version is 307.0.0,but get version error

### ISSUE THREAD

**Issue by chobijaeyu** [GoogleCloudPlatform/cloud-code-vscode#288] opened 2020-08-26 04:46 UTC
**Environment**:
Extension version: v1.5.1
VSCode version:1.48.2
OS:  Darwin x64 17.7.0

**Description**:
I'm confused.
btw, I used brew install google-cloud-sdk.

![スクリーンショット 2020-08-26 13 39 52](https://user-images.githubusercontent.com/25117318/91256211-b58eb180-e7a1-11ea-8fce-e3b669316b02.png)

**Comment by j-windsor** [comment] 2020-08-27 16:37
Hi @chobijaeyu. This is indeed strange. If you are trying to use the google-cloud-sdk in your `PATH`, Can you confirm you have opted out of the extension's automatic dependency management? You can go to VSCode settings and find the value of `cloudcode.autoDependencies` to find out. I will see if I can repro with brew.

**Comment by chobijaeyu** [comment] 2020-08-28 01:48
@j-windsor thanks for your reply. I checked the setting is on by default.

**Comment by j-windsor** [comment] 2020-08-28 16:45
Thanks! Can you report the output of this command?
```
~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud version
```
(We are using an installation of gcloud we manage at this Application Support directory when managed dependencies is on)

**Comment by chobijaeyu** [comment] 2020-08-31 01:06
goods day. @j-windsor 
you are right. here is problem.

```
╰─ ~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud version
Google Cloud SDK 299.0.0
alpha 2020.06.26
beta 2020.06.26
bq 2.0.58
core 2020.06.26
gsutil 4.51
kubectl 2020.05.01
minikube
skaffold
```

**Comment by sivakku** [comment] 2020-08-31 16:23
Indeed it is strange. i am using version 1.5.1 extension but can't reproduce, looks like something is preventing from getting gcloud upgraded. Can you wipe the cloud-code/installer directory?

```
$ /Users/sivakk/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud version
Google Cloud SDK 307.0.0
alpha 2020.08.21
beta 2020.08.21
bq 2.0.59
core 2020.08.21
gsutil 4.53
kubectl 1.15.11
minikube 
skaffold 
```

**Comment by kschaab** [comment] 2020-08-31 17:28
@chobijaeyu Could you try running `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud components update` and let us know what happens?

**Comment by chobijaeyu** [comment] 2020-09-01 01:12
@kschaab 
good morning.

It just update...

```
╰─ sudo ~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud components update
Password:


Your current Cloud SDK version is: 299.0.0
You will be upgraded to version: 307.0.0

╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: BigQuery Command Line Tool                 ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: BigQuery Command Line Tool (Platform Sp... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Cloud SDK Core Libraries                   ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Cloud SDK Core Libraries (Platform Spec... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Cloud Storage Command Line Tool            ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Cloud Storage Command Line Tool (Platfo... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Minikube                                   ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: Skaffold                                   ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: anthoscli                                  ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: gcloud cli dependencies                    ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: kubectl                                    ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Uninstalling: kubectl                                    ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: BigQuery Command Line Tool                   ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: BigQuery Command Line Tool (Platform Spec... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud SDK Core Libraries                     ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud SDK Core Libraries (Platform Specific) ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud Storage Command Line Tool              ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Cloud Storage Command Line Tool (Platform... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Minikube                                     ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Skaffold                                     ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: anthoscli                                    ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: gcloud cli dependencies                      ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: kubectl                                      ═╣
╠════════════════════════════════════════════════════════════╣═══╝
╠═ Installing: kubectl                                      ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝

Performing post processing steps...done.

Update done!

To revert your SDK to the previously installed version, you may run:
  $ gcloud components update --version 299.0.0

WARNING:   There are other instances of Google Cloud Platform tools on your system PATH.
  Please remove the following to avoid confusion or accidental invocation:

/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/bq
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/git-credential-gcloud.sh
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gsutil
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/docker-credential-gcloud
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud

```


seem to there is two independent  google-cloud-sdk in my mac.

**Comment by redborian** [comment] 2020-09-09 17:39
Thanks for the update, @chobijaeyu. I will go ahead and close this issue

**Closed by redborian** 2020-09-09 17:39 UTC
Labels: bug, p1
