### ISSUE TITLE
Kubernetes Explorer does not update to reflect that cluster has been deleted

### ISSUE THREAD

**Issue by IsaacPD** [GoogleCloudPlatform/cloud-code-vscode#300] opened 2020-09-25 22:31 UTC
**Environment**:
Extension version: v1.5.3
VSCode version: 1.50.0-insider
OS: Catalina 10.15.6

**Description**:
I had created a GKE cluster using the interface on VSCode but there was an error and so I had to delete it. I deleted the cluster successfully in VSCode, but the Kubernetes Explorer panel did not update to reflect that the cluster did not exist anymore even after I refreshed it. And so I had to manually edit the KubeConfig to remove it.
[
<img width="1792" alt="Screen Shot 2020-09-25 at 6 21 00 PM" src="https://user-images.githubusercontent.com/12650821/94321207-fb839480-ff5c-11ea-85bb-9b45a16dfae5.png">
](url)
**Repro step**:
1. Create GKE (Have it encounter an error?)
2. Delete GKE Cluster
3. Refresh Kubernetes Explorer panel

**Comment by kschaab** [comment] 2020-12-07 21:36
This is currently working as intended as deleting a GKE cluster does not update your kubernetes config file.  We are looking into solutions to maybe allow cleanup of this file automatically.

**Comment by j-windsor** [comment] 2021-01-07 23:27
Closing as wontfix

**Closed by j-windsor** 2021-01-07 23:27 UTC
Labels: kind/enhancement
