### ISSUE TITLE
[Question] How to define and pass env variables to skaffold using cloud code extension?

### ISSUE THREAD

**Issue by cheburakshu** [GoogleCloudPlatform/cloud-code-vscode#715] opened 2023-01-18 22:50 UTC
**Use case**
There are multiple ways to use environment variables in Skaffold (profiles, docker build args etc), but no way to pass them from launch.json in cloud code extension. I have seen multiple recommendations to use profiles in the issues section of this repo, but the profiles themselves can get activated but not define any env variable. Would be super helpful if there is ability to define env vars in launch.json.
There are quite a lot of extensions that provide this capability to define env vars using `"env"` keyword, would be nice to add and use it in cloud code extension as well.

**Comment by ChaseMor** [comment] 2023-01-18 23:33
Unfortunately, defining environment variables in the launch config is not currently supported. Appreciate your feedback! This is on our radar as something to add, just haven't gotten to it yet.

One possible workaround, is that when starting the VSCode process, set the environment variable in the terminal. Something like `FOO=bar; code ./path-to-workspace`. Then, when the skaffold process gets created, it will have these env vars set and be able to use them.

**Comment by ChaseMor** [comment] 2023-01-18 23:33
Closing this as this seems to be a duplicate of #624.

**Closed by ChaseMor** 2023-01-18 23:33 UTC

**Comment by cheburakshu** [comment] 2023-01-19 00:26
based on this ticket here, it should have been added and working nearly 2 years ago. https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/378.
