### ISSUE TITLE
Message: Request initialize failed with message: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mrdulin** [GoogleCloudPlatform/cloud-code-vscode#108] opened 2019-05-19 14:55 UTC
**Environment**:
Extension version: 0.0.8
VSCode version: 1.34.0
OS: macOS mojave 

**Description**:
I install this extension the first time and got this error.

> [Error - 10:43:28 PM] Server initialization failed.
  Message: Request initialize failed with message: ENOENT: no such file or directory, open '/Users/elsa/workspace/github.com/mrdulin/dotfiles/examples/connect-multiple-containers/docker-compose.yaml'
  Code: -32603 

**Repro step**:

I put `.zshrc` in dotfiles directory and create a soft link for `.zshrc` file to `~/.zshrc`

Here is my dotfiles: https://github.com/mrdulin/dotfiles

I clone this repo in the path of my local desktop: `/Users/elsa/workspace/github.com/mrdulin/dotfiles`

Why this extension try to open the `docker-compose.yaml` file in my other repo?

Reload vscode window, still get this error.

**Comment by iantalarico** [comment] 2019-05-20 11:08
@sujit-kamireddy @quoctruong @redborian @pongad Can one of you take a look at this?

**Comment by pongad** [comment] 2019-05-22 20:43
@redborian I *think* this is coming from the YAML language server. (The "Server initialization failed" looks like VSCode error when lang server crashes.)

I can't seem to reproduce this though. I feel like something is confused about creating absolute paths somehow.

@mrdulin Can we have additional details? Do you have multiple folders open etc?

**Comment by mrdulin** [comment] 2019-05-23 02:24
Here is my vscode workspace and projects in it. 

- vscode workspace
  - docker-research
    - examples
      - connect-multiple-containers
        - docker-compose.yaml
  - dotfiles
  
It seems cloud code try to read `docker-research/examples/connect-multiple-containers/docker-compose.yaml` file.

**Comment by marcfong** [comment] 2019-06-10 08:20
I get the same error as well after using the "Apply current YAML to Kuberenetes" command.

The first time i run the command it succeeds to apply the active yaml to my cluster.
The second time i run it again, this error pops up.

**Comment by redborian** [comment] 2019-06-10 14:08
@mrdulin We are currently trying to parse all yaml files in the current workspace. We will be more smarter to ignore certain known files in the future release.

**Comment by redborian** [comment] 2019-06-10 14:09
@macfong It looks like somehow the yaml file is unreachable to VSCode. Can you manually check if that file indeed exists on disk?

**Comment by mrdulin** [comment] 2019-06-10 14:44
@redborian Got it. That's the reason. Thanks for reply.

**Comment by marcfong** [comment] 2019-06-11 02:36
@redborian that path and file does not exist. However, that is not where my actual YAML manifest is stored. The plugin must be reading the wrong file path from vscode, some temp file or something.

The first time I try the command against the YAML file open in the editor it works. Once I try the command again immediately, I hit that error.

**Comment by redborian** [comment] 2019-06-11 15:00
Thanks for the explanation @marcfong. From the temp file name it is clear that you are somehow viewing the server definition of a resource and trying to apply the changes.
How was the server definition file opened after applying kubernetes yaml from a local yaml file? Are you already in the server definition file, making changes to it and trying to apply it?

**Comment by redborian** [comment] 2019-06-14 18:03
I am able to repro the issue @marcfong. We will fix it in the next release. As a workaround, you can use `kubectl apply -f <filename>` command from the terminal.

**Comment by sujit-kamireddy** [comment] 2019-07-12 17:20
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.

**Closed by sujit-kamireddy** 2019-07-12 17:20 UTC
Labels: bug, in-next-release
